### ISSUE TITLE
URGENT: Latest release breaks old aiohttp installs

### ISSUE THREAD

**Issue by Mackey22** [aio-libs/yarl#192]
Use case:

`virtualenv env -p python3.6`
`source env/bin/activate`
`pip install aiohttp==2.2.5`
`python`
`>>> import aiohttp`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/James/Documents/env/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Users/James/Documents/env/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/Users/James/Documents/env/lib/python3.6/site-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/Users/James/Documents/env/lib/python3.6/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/Users/James/Documents/env/lib/python3.6/site-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/Users/James/Documents/env/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/Users/James/Documents/env/lib/python3.6/site-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/Users/James/Documents/env/lib/python3.6/site-packages/yarl/__init__.py", line 232, in __init_subclass__
    "is forbidden".format(cls))```

Backwards compatibility with old aiohttp installs is required for my company's production use case. Please update on this issue.

**Comment by asvetlov** [comment]
Please pin yarl in your requirements: aiohttp==2.2.5 is not supported more than a half year.
