### ISSUE TITLE
TypeError in URL.with_query

### ISSUE THREAD

**Issue by dyus** [aio-libs/yarl#24]
Hello, I have a problem with generating query_params. I try to make query
```python
session = aiohttp.ClientSession()
session.request('get', 'some_url', {'p1': 1, 'p1': 2, 'p2': 3})
```
and got TypeError
```python
  File "/lib/python3.5/site-packages/aiohttp/client.py", line 553, in __await__
    resp = yield from self._coro
  File "/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
    proxy=proxy, proxy_auth=proxy_auth, timeout=timeout)
  File "lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 79, in __init__
    url2 = url.with_query(params)
  File "/lib/python3.5/site-packages/yarl/__init__.py", line 675, in with_query
    raise TypeError("Invalid variable type")
TypeError: Invalid variable type
```
After some research I understand that Mapping with key: Sequence works with `MultiDict`. But this is not obvious. Maybe it should cast  `dict` into `MultiDict` or return more descriptive warning or add logic for parsing Sequences in Mapping section

**Comment by asvetlov** [comment]
I prefer first option:  casting `dict` into `MultiDict`.
Would you provide a patch?

**Comment by dyus** [comment]
Yes, I'll send pr today or tomorrow

**Comment by asvetlov** [comment]
> After some research I understand that Mapping with key: Sequence works with `MultiDict`.

@dyus please elaborate.
```
>>> MultiDict(a=[1, 2, 3])
<MultiDict('a': [1, 2, 3])>
```
Result is a dict with single key and list as value.
It's not the same as three items with the same key:
```
>>> MultiDict([('a', 1), ('a', 2), ('a', 3)])
<MultiDict('a': 1, 'a': 2, 'a': 3)>
```

**Comment by dyus** [comment]
You mean `dict_to_multidict` should convert `{'a': [1, 2, 3}` into `<MultiDict('a': [1, 2, 3])>'?
This  result is not a valid structure for `URL.with_query` method.
```python
n [5]: u = yarl.URL('http://123/')
In [6]: u.with_query(multidict.MultiDict({'a': [1,2,3]}))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-6675a96330d2> in <module>()
----> 1 u.with_query(multidict.MultiDict({'a': [1,2,3]}))

/Users/a.zdanchuk/Envs/mobile_api/lib/python3.5/site-packages/yarl/__init__.py in with_query(self, *args, **kwargs)
    673                 #     v = '&'.join([str(i) for i in v])
    674                 else:
--> 675                     raise TypeError("Invalid variable type")
    676                 lst.append(quoter(k)+'='+quoter(v))
    677             query = '&'.join(lst)

TypeError: Invalid variable type
```

**Comment by asvetlov** [comment]
I don't want to support list values but added more verbose error messages: 4b9a94a
