### ISSUE TITLE
1.9.4: documentation build fail

### ISSUE THREAD

**Issue by kloczek** [aio-libs/yarl#970]
### Describe the bug

On first look looks like `yarl` documentation is not ready for `sphinx` >= 7.1.x

### To Reproduce

`sphinx-build -n -T -b man docs build/sphinx/man`

### Expected behavior

Documentation should build correctly.

### Logs/tracebacks

<details>
<summary>documentation build output</summary>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://multidict.aio-libs.org/en/stable/objects.inv...
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 363, in get_outdated_docs
    towncrier_fragment_paths = _lookup_towncrier_fragments(
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 119, in _lookup_towncrier_fragments
    towncrier_config = get_towncrier_config(
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/_towncrier.py", line 27, in get_towncrier_config
    return load_config_from_file(str(project_path), str(final_config_path))
  File "/usr/lib/python3.8/site-packages/towncrier/_settings/load.py", line 104, in load_config_from_file
    return parse_toml(directory, config)
  File "/usr/lib/python3.8/site-packages/towncrier/_settings/load.py", line 114, in parse_toml
    raise ConfigError("No [tool.towncrier] section.", failing_option="all")
towncrier._settings.load.ConfigError: No [tool.towncrier] section.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 287, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 381, in read
    for docs in self.events.emit('env-get-outdated', self.env, added, changed, removed):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7f5eccf3ab20>> for event 'env-get-outdated' threw an exception (exception: No [tool.towncrier] section.)

Extension error (sphinxcontrib.towncrier.ext):
Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7f5eccf3ab20>> for event 'env-get-outdated' threw an exception (exception: No [tool.towncrier] section.)
```
</details>

### Python Version
3.8.18

### OS
Linux x86/64

### Additional context

<details>
<summary>List of installed modules in build env:</summary>

```console
Package                       Version
----------------------------- -------
alabaster                     0.7.13
Babel                         2.13.1
build                         1.0.3
charset-normalizer            3.3.2
click                         8.1.7
cppclean                      0.13
Cython                        3.0.5
distro                        1.8.0
dnf                           4.18.1
docutils                      0.20.1
exceptiongroup                1.1.3
expandvars                    0.12.0
gpg                           1.23.0
idna                          3.6
imagesize                     1.4.1
importlib-metadata            7.0.0
importlib-resources           6.1.1
incremental                   22.10.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.2
libdnf                        0.72.0
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
mdit-py-plugins               0.4.0
mdurl                         0.1.2
multidict                     6.0.4
myst-parser                   2.0.0
packaging                     23.2
pluggy                        1.3.0
Pygments                      2.17.2
pyproject_hooks               1.0.0
pytest                        7.4.3
python-dateutil               2.8.2
pytz                          2023.3
PyYAML                        6.0.1
requests                      2.31.0
setuptools                    69.0.2
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        7.1.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.9
sphinxcontrib-towncrier       0.3.1a3
tomli                         2.0.1
towncrier                     23.11.0
urllib3                       1.26.18
wheel                         0.42.0
zipp                          3.17.0
```
</details>

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
It does build correctly in CI and RTD. There must be a problem in your env.

**Comment by kloczek** [comment]
I don't see anything about building documentation in any file from https://github.com/aio-libs/yarl/tree/master/.github/workflows
```console
[tkloczko@pers-jacek yarl-1.9.4]$ grep -r sphinx .github/workflows/
[tkloczko@pers-jacek yarl-1.9.4]$
```

**Comment by webknjaz** [comment]
https://github.com/aio-libs/yarl/blob/master/.readthedocs.yaml
https://github.com/aio-libs/yarl/blob/master/.github/workflows/reusable-linters.yml

**Comment by kloczek** [comment]
Did you try to use command which I'm using?
